[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/groupes-de-travaux/"
to = "/groupes/"

[[redirects]]
from = "/groupes-de-travaux/groupe-3-risques-de-lia-dans-leducation/"
to = "/groupes/risques-de-lia-dans-leducation/"

[[redirects]]
from = "/groupes-de-travaux/ressources/"
to = "/ressources/"

[[redirects]]
from = "/groupes-de-travaux/groupe-5-comment-peut-on-evaluer-un-eleve-sur-des-travaux-personnels/"
to = "/groupes/comment-peut-on-evaluer-un-eleve-sur-des-travaux-personnels/"

[[redirects]]
from = "/actualites/2025-03-24-on-retient-moins-dinformations-et-de-methodes-si-on-demande-a-chatgpt/"
to = "/actualites/2025-03-10-on-retient-moins-dinformations-et-de-methodes-si-on-demande-a-chatgpt/"

[[redirects]]
from = "/groupe-2-comment-utiliser-lia-pour-apprendre-mieux/"
to = "/groupes/comment-utiliser-lia-pour-apprendre-mieux/"

[[redirects]]
from = "/groupes-de-travaux/groupe-4-faut-il-former-tous-les-apprenants-et-formateurs/"
to = "/groupes/faut-il-former-tous-les-apprenants-et-formateurs/"

[[redirects]]
from = "/groupes-de-travaux/groupe-1-quelles-competences-et-metiers-demain/"
to = "/groupes/quelles-competences-et-metiers-demain/"

[[redirects]]
from = "/groupes-de-travaux/groupe-2-comment-utiliser-lia-pour-apprendre-mieux/"
to = "/groupes/comment-utiliser-lia-pour-apprendre-mieux/"

